### ISSUE TITLE
Cleanup Spawn Menu Code

### ISSUE THREAD

**Issue by dhkatz** [DoctorJew/star-wars-vehicles-redux#1]
The current spawn menu code is really messy because it was just copied from the Garry's Mod source code without much care for readability.

**Comment by Servius** [comment]
Ive noticed that ships/weapons sharing the same printname cancel each other out.

**Comment by dhkatz** [comment]
That is normal behavior for Garry's Mod entities/weapons. I can't work around that without putting an _2, _3 at the end of names for duplicates, but this would mess with developers that expect their ships to be named a certain thing.

**Comment by Servius** [comment]
In the vanilla spawnmenu my weapons+vehicles didnt shut each other off as long as their file names were differnet. ie Umbaran Rifle; umbaran_rifle_red.lua Umbaran Rifle; umbran_rifle_blue.lua etc.
This same behavior was also present in the VJ Base menu system where you could have variants sharing the same name without shutting each other off as long as they have different code references.

**Comment by dhkatz** [comment]
Oh you are talking about print names vs entity names. Yeah that should be a bug then I'll fix it.

**Comment by Servius** [comment]
As it is liams old menu would shut off weapons/vehicles that shared the same print name even when using different entity names. 

http://prntscr.com/kz67eo

**Comment by dhkatz** [comment]
Alright this isn't actually something I have to fix. In fact you can work around this right now in the current base by changing:
```lua
list.Set("SWVRVehicles", ENT.PrintName, ENT)
```
to
```lua
list.Set("SWVRVehicles", ENT.Folder, ENT)
```

This is because the PrintName may not be unique but the Folder will always be unique to the entity.
