### ISSUE TITLE
Do not add resource files but workshop addon 

### ISSUE THREAD

**Issue by P4sca1** [DoctorJew/star-wars-vehicles-redux#13]
**Is your feature request related to a problem? Please describe.**
At the moment resources are added with `resource.AddFile` which is bad for most servers as it is not common to have FastDL setup. This problem results in high loading (download) times. 

**Describe the solution you'd like**
Add the resources to workshop on release and replace all falls to `resource.AddFile` with a single call to `resource.AddWorkshop`.

**Comment by dhkatz** [comment]
They're only there so it's easier to test changes on multiplayer without having anything uploaded to the workshop. They will be removed on release.
