### ISSUE TITLE
Cursor Controls

### ISSUE THREAD

**Issue by ThanosorDFaceG** [DoctorJew/star-wars-vehicles-redux#18]
While I'm not completely sure if this should be considered a bug (after all it was in the original version of the base), mouse controls are always inverted in random directions when in first person and spinning. Don't know if this can be fixed.

**To Reproduce**
1. Spawn in one of the vehicles.
2. Go in first person (pretty sure default key is still Alt).
3. Spin using A or D keys.
4. Try moving camera with mouse.

**Expected behavior**
Vehicle and camera should move in opposite directions of mouse (depending on angle of vehicle).

**Screenshots**
No screenshots really. It would just look like I'm flying normally and you can't really tell without replicating it yourself.

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
Just thought fixing this would be nice, since it's been a problem since the original SW vehicle base.

**Comment by dhkatz** [comment]
Actually reworking the flight model today so this should probably be fixed anyway
