### ISSUE TITLE
Suggestion for optimizing code used in the ENT:HUDDrawCrosshair()

### ISSUE THREAD

**Issue by VaasKahnGrim** [DoctorJew/star-wars-vehicles-redux#24]
File in question 'lua/entities/swvr_base/cl_init.lua'

sorry in advance if a github issue is the wrong way of sending stuff(I hate trying to use github lmao, too confusing to use for me)

Basically I was reading through the file to see how the code for vehicle HUDs worked and noticed that surface. surface.DrawCircle was being used in the ENT:HUDDrawCrosshair() function. this post is about suggesting the use of http://wiki.garrysmod.com/page/surface/DrawTexturedRect with a circletexture instead.

Both would create the intended outcome, however calculating a circle in surface is much slower then simply drawing a texture with transparency instead. Especially when things like HUDPaint have to rerender everything on each frame.

**Comment by dhkatz** [comment]
That was really only a test to see if I could design another reticle. `ENT:HUDDrawCrosshair()` isn't actually being called currently. Thank you for reminding me to clean it up.
