### ISSUE TITLE
Release To-do List

### ISSUE THREAD

**Issue by dhkatz** [DoctorJew/star-wars-vehicles-redux#6]
The following things need to be addressed before I can make a release:

- [x] Wings
- [ ] Fully Implemented Controls

If anyone can thing of anything other absolute requirements for release please tell me here @Servius

**Comment by Servius** [comment]
Documentation would probably last thing you would do.

**Comment by dhkatz** [comment]
Seems very small model scales cause issues with clientside cockpits, not really going to fix right now as not many ships use client cockpits and I doubt many people will want tiny model scales.
